name: build
on: [push, pull_request]
jobs:

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: non-ros-deps
      run: |
        sudo apt update
        sudo apt install -y wget
        echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
        wget https://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
        
        sudo apt update && sudo apt install \
          git cmake python3-vcstool curl \
          qt5-default \
          libboost-system-dev libboost-date-time-dev libboost-regex-dev libboost-random-dev \
          python3-shapely python3-yaml python3-requests \
          libignition-common3-dev libignition-plugin-dev \
          g++-8 \
          -y

    - name: workspace
      run: |
        mkdir -p rmf_demos_ws/src
        cd rmf_demos_ws/src
        git clone https://github.com/osrf/rmf_core.git
        git clone https://github.com/osrf/traffic_editor.git
        git clone https://github.com/osrf/rmf_schedule_visualizer.git

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: rmf_demos_ws/src/rmf_demos

    - name: ros-deps
      run: |
        cd rmf_demos_ws
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro eloquent -yr
    - name: build
      shell: bash
      run: |
        cd rmf_demos_ws
        source /opt/ros/eloquent/setup.bash
        CXX=g++-8 colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE -DNO_DOWNLOAD_MODELS=True --packages-up-to \
          demos \
          rmf_demo_assets \
          rmf_demo_maps \
          rmf_demo_tasks \
          rmf_gazebo_plugins \
          rmf_rviz_plugin 