name: build
on: push
jobs:

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: non-ros-deps
      run: |
        sudo apt update && sudo apt install \
          git cmake wget python3-vcstool \
          qt5-default libeigen3-dev \
          libccd-dev libfcl-dev \
          libyaml-cpp-dev libwebsocketpp-dev \
          libboost-all-dev curl \
          python3-shapely python3-yaml \
          python3-requests \
          -y
    - name: workspace
      run: |
        cd /home/
        mkdir -p rmf_demos_ws/src
        cd /home/rmf_demos_ws
        wget https://raw.githubusercontent.com/osrf/rmf_demos/master/rmf_demos.repos
        vcs import src < rmf_demos.repos
    - name: ros-deps
      run: |
        cd /home/rmf_demos_ws
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro eloquent \
          -y --skip-keys "websocketpp ament_python"
    - name: checkout
      shell: bash
      run: |
        cd /home/rmf_demos_ws/src/rmf/rmf_demos
        git checkout "${GITHUB_REF:11}"
    - name: build
      shell: bash
      run: |
        cd /home/rmf_demos_ws
        source /opt/ros/eloquent/setup.bash
        colcon build
